#!/bin/bash
#
# THIS SCRIPT WILL OPEN PROGRAM FROM THE COMMAND LINE
# AND WILL RELEASE IT FROM COMMAND, ALLOWING TO CONTINUE
# WORKING FROM THE COMMAND LINE, TO THE POINT OF CLOSING
# THE COMMAND LINE WITH OUT CLOSSING THE PROGRAM.
#
# IT USES TWO ARGUMENTS:
# $1 IS THE NAME OF THE FILE TO OPEN.
# $2 IS THE NAME OF THE PROGRAM,

($2 $1 &> /dev/null &)
